-- Generated by scripts/build-seed.mjs. Do not edit by hand.
begin;
insert into sites (id, name, kind) values ('EAS','Eastcote','restaurant'),('WEM','Wembley','production'),('SYD','Sydenham','restaurant');
update sites set status='closed', closed_reason='Closed until reopening (owner decision 9 Oct 2026)', closed_at=now() where id='SYD';
-- Limits must be confirmed by the owner against the approved HACCP plan before go-live (approved_by stays null until then).
insert into temp_rules (code, label, target_max, target_min, legal_max, legal_min) values
 ('F','Fridge / chilled', 5, null, 8, null),
 ('Z','Freezer', -18, null, null, null),
 ('C','Cooking core', null, 75, null, 75);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-FOH-OPEN', 'EAS', 'FOH Opening', 'FOH', 'Before doors open', '11:30', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-FOH-OPEN', 1, 'published', 'EAS- FOH Opening Closing + SYD FOH (counter desk items)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Dining area', 'Set and adjust menus on tables', 'tick', null, null, null),
 ((select id from v), 2, 'Dining area', 'Straighten polaroids on the wall', 'tick', null, null, null),
 ((select id from v), 3, 'Dining area', 'Straighten chairs', 'tick', null, null, null),
 ((select id from v), 4, 'Dining area', 'Dim lights on, brightness set', 'tick', null, null, null),
 ((select id from v), 5, 'Dining area', 'Coat hanging area tidy', 'tick', null, null, null),
 ((select id from v), 6, 'Dining area', 'Air con settings checked', 'tick', null, null, null),
 ((select id from v), 7, 'Dining area', 'Air freshener sprayed along the dining area', 'tick', null, null, null),
 ((select id from v), 8, 'Counter desk', 'PC, POS and delivery apps switched on', 'tick', null, null, null),
 ((select id from v), 9, 'Counter desk', 'Stock items updated in POS', 'tick', null, null, 'from SYD'),
 ((select id from v), 10, 'Counter desk', 'Old receipts cleared', 'tick', null, null, 'from SYD'),
 ((select id from v), 11, 'Counter desk', 'No unprocessed sales left in POS', 'tick', null, 'If there are, tell the manager', 'from SYD'),
 ((select id from v), 12, 'Counter desk', 'Music playlist on', 'tick', null, null, 'from SYD'),
 ((select id from v), 13, 'Bar and service', 'Beer tap on and set to level 7', 'tick', null, 'Level 7', null),
 ((select id from v), 14, 'Bar and service', 'Pho condiments restocked', 'tick', null, 'Sweet chilli onion, hoisin, lime', null),
 ((select id from v), 15, 'Bar and service', 'Drink mix jugs checked and restocked', 'tick', null, 'Coffee, lemonade, tea', null),
 ((select id from v), 16, 'Bar and service', 'Che items restocked in fridge', 'tick', null, null, null),
 ((select id from v), 17, 'Bar and service', 'Glasses polished and restocked', 'tick', null, null, null),
 ((select id from v), 18, 'Bar and service', 'Dine-in cutlery and plates polished and restocked', 'tick', null, null, null),
 ((select id from v), 19, 'Bar and service', 'Takeaway packaging, cutlery and utensils restocked', 'tick', null, null, null),
 ((select id from v), 20, 'Bar and service', 'Dip saucers counted', 'tick', null, null, 'from SYD'),
 ((select id from v), 21, 'Customer toilet', 'Toilet roll restocked, 1 spare on the shelf', 'tick', null, null, null),
 ((select id from v), 22, 'Customer toilet', 'Hand soap restocked', 'tick', null, null, null),
 ((select id from v), 23, 'Customer toilet', 'Hot water working', 'tick', null, null, null),
 ((select id from v), 24, 'Customer toilet', 'Air freshener sprayed', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-FOH-CLOSE', 'EAS', 'FOH Closing', 'FOH', 'After last customer', '22:30', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-FOH-CLOSE', 1, 'published', 'EAS- FOH Opening Closing + SYD FOH (counter desk, labelling)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Dining area', 'Tables cleaned', 'tick', null, null, null),
 ((select id from v), 2, 'Dining area', 'Floors hoovered and mopped', 'tick', null, null, null),
 ((select id from v), 3, 'Counter desk', 'All unprocessed sales closed', 'tick', null, null, 'from SYD'),
 ((select id from v), 4, 'Counter desk', 'End-of-day sales entered', 'number', null, 'Enter the total from the POS Z-report', 'from SYD'),
 ((select id from v), 5, 'Counter desk', 'Mobile, card reader and delivery tablets on charge', 'tick', null, null, 'from SYD'),
 ((select id from v), 6, 'Counter desk', 'Counter desk tidied', 'tick', null, null, 'from SYD'),
 ((select id from v), 7, 'Bar and service', 'Sauce bottles cleaned, wiped and covered', 'tick', null, null, null),
 ((select id from v), 8, 'Bar and service', 'Countertop fridge contents moved to undercounter fridge', 'tick', null, null, null),
 ((select id from v), 9, 'Bar and service', 'Countertop fridge switched off', 'tick', null, null, null),
 ((select id from v), 10, 'Bar and service', 'Undercounter fridge lights off', 'tick', null, null, 'from SYD'),
 ((select id from v), 11, 'Bar and service', 'All fridge contents stored correctly and labelled', 'tick', null, null, 'from SYD'),
 ((select id from v), 12, 'Customer toilet', 'Toilet and mirror clean', 'tick', null, null, 'from SYD'),
 ((select id from v), 13, 'Customer toilet', 'Toilet bin emptied into main bin', 'tick', null, null, null),
 ((select id from v), 14, 'Customer toilet', 'Tissue rolls replenished', 'tick', null, null, 'from SYD');
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-FOH-CLEAN', 'EAS', 'FOH Daily Clean', 'FOH', 'End of each shift', '22:30', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-FOH-CLEAN', 1, 'published', 'EAS- FOH Cleaning Schedule', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Dining area', 'Menus wiped', 'tick', null, null, null),
 ((select id from v), 2, 'Dining area', 'Tables and chairs cleaned and sanitised', 'tick', null, null, null),
 ((select id from v), 3, 'Dining area', 'Bench ledges and divider frames wiped', 'tick', null, null, null),
 ((select id from v), 4, 'Dining area', 'Side ledges wiped', 'tick', null, null, null),
 ((select id from v), 5, 'Dining area', 'Standing cabinet wiped', 'tick', null, null, null),
 ((select id from v), 6, 'Dining area', 'Polaroids and wire straightened', 'tick', null, null, null),
 ((select id from v), 7, 'Dining area', 'Floor vacuumed and mopped with floor cleaner', 'tick', null, null, null),
 ((select id from v), 8, 'Front area', 'Door handle wiped', 'tick', null, null, null),
 ((select id from v), 9, 'Front area', 'Counter wiped', 'tick', null, null, null),
 ((select id from v), 10, 'Front area', 'Counter devices wiped', 'tick', null, 'PC, printers, phones, keyboard', null),
 ((select id from v), 11, 'Bar area', 'Beer tap machine cleaned and sanitised', 'tick', null, null, null),
 ((select id from v), 12, 'Bar area', 'Beer tap cupboard wiped', 'tick', null, null, null),
 ((select id from v), 13, 'Bar area', 'Prep table cleaned and sanitised', 'tick', null, null, null),
 ((select id from v), 14, 'Bar area', 'Drainer mats washed', 'tick', null, null, null),
 ((select id from v), 15, 'Bar area', 'Bar fridge doors, handles and glass wiped', 'tick', null, null, null),
 ((select id from v), 16, 'Bar area', 'Inside bar fridges sanitised', 'tick', null, null, null),
 ((select id from v), 17, 'Bar area', 'Mini freezer wiped', 'tick', null, null, null),
 ((select id from v), 18, 'Customer toilet', 'Mirror, basin, toilet and tank cleaned', 'tick', null, null, null),
 ((select id from v), 19, 'Customer toilet', 'Light switch and door handles wiped', 'tick', null, null, null),
 ((select id from v), 20, 'Customer toilet', 'Tissue and soap dispensers wiped', 'tick', null, null, null),
 ((select id from v), 21, 'Customer toilet', 'Under-sink cupboard and handle wiped', 'tick', null, null, null),
 ((select id from v), 22, 'Customer toilet', 'Overhead cupboard and shelf wiped', 'tick', null, null, null),
 ((select id from v), 23, 'Customer toilet', 'Bin emptied', 'tick', null, null, null),
 ((select id from v), 24, 'Customer toilet', 'Floor swept and mopped', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-FOH-WEEKLY', 'EAS', 'FOH Weekly & Monthly Clean', 'FOH', 'Weekly / monthly', null, false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-FOH-WEEKLY', 1, 'published', 'EAS- FOH Cleaning Schedule (duplicate row removed)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Every week', 'Light pendants wiped', 'tick', null, null, null),
 ((select id from v), 2, 'Every week', 'Wall tiles wiped', 'tick', null, null, null),
 ((select id from v), 3, 'Every week', 'Door and window panels cleaned', 'tick', null, null, null),
 ((select id from v), 4, 'Every week', 'Top storage doors wiped', 'tick', null, null, null),
 ((select id from v), 5, 'Every month', 'Tracking lights wiped', 'tick', null, null, null),
 ((select id from v), 6, 'Every month', 'Air con cleaned', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-FOH-TOILET', 'EAS', 'Toilet Check', 'FOH', 'Every 2 hours in service', null, false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-FOH-TOILET', 1, 'published', 'Toilet Check (PDF)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Quick check', 'Toilet clean and flushed', 'tick', null, null, null),
 ((select id from v), 2, 'Quick check', 'Toilet roll, soap and paper towels stocked', 'tick', null, null, null),
 ((select id from v), 3, 'Quick check', 'Floor dry and bin not overflowing', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-BAR-PREP', 'EAS', 'Bar & Counter Prep', 'FOH', 'Before service', '11:30', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-BAR-PREP', 1, 'published', 'Bar Area Prep Work', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'General', 'Limes cut into wedges', 'tick', null, null, null),
 ((select id from v), 2, 'General', 'Sweet chilli onions checked', 'tick', null, null, null),
 ((select id from v), 3, 'General', 'Packaging restocked', 'tick', null, null, null),
 ((select id from v), 4, 'General', 'Drinks restocked', 'tick', null, null, null),
 ((select id from v), 5, 'Banh mi', 'Banh mi stock checked', 'tick', null, null, null),
 ((select id from v), 6, 'Banh mi', 'Coriander stalks cut to length', 'tick', null, null, null),
 ((select id from v), 7, 'Banh mi', 'Cucumber sliced', 'tick', null, null, null),
 ((select id from v), 8, 'Banh mi', 'Chillies sliced', 'tick', null, null, null),
 ((select id from v), 9, 'Banh mi', 'Spring onions finely shredded', 'tick', null, null, null),
 ((select id from v), 10, 'Banh mi', 'House mayo checked', 'tick', null, null, null),
 ((select id from v), 11, 'Banh mi', 'Pickle restocked', 'tick', null, null, null),
 ((select id from v), 12, 'Banh mi', 'Pate restocked', 'tick', null, null, null),
 ((select id from v), 13, 'Summer rolls', 'Coriander leaves picked', 'tick', null, null, null),
 ((select id from v), 14, 'Summer rolls', 'Mint leaves picked', 'tick', null, null, null),
 ((select id from v), 15, 'Summer rolls', 'Romaine cut to size', 'tick', null, null, null),
 ((select id from v), 16, 'Summer rolls', 'Bun portioned', 'tick', null, null, null),
 ((select id from v), 17, 'Summer rolls', 'Sauces restocked', 'tick', null, null, null),
 ((select id from v), 18, 'Drinks', 'Ice broken', 'tick', null, null, null),
 ((select id from v), 19, 'Drinks', 'Water containers refilled and frozen', 'tick', null, null, null),
 ((select id from v), 20, 'Drinks', 'Lemons sliced', 'tick', null, null, null),
 ((select id from v), 21, 'Drinks', 'Mix jugs checked', 'tick', null, null, null),
 ((select id from v), 22, 'Drinks', 'Che restocked', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-BOH-OPEN', 'EAS', 'BOH Opening', 'BOH', 'Before service', '11:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-BOH-OPEN', 1, 'published', 'No EAS BOH file found: based on SYD BOH Opening & Closing', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Start of shift', 'Uniform on, hands washed, hairnet on', 'tick', null, null, null),
 ((select id from v), 2, 'Start of shift', 'Appliances on, water boiling for noodles and bun', 'tick', null, null, null),
 ((select id from v), 3, 'Start of shift', 'Fridge and freezer temperatures recorded', 'tick', null, 'Opens the Temperature Check', null),
 ((select id from v), 4, 'Start of shift', 'Stock levels and use-by dates checked', 'tick', null, null, null),
 ((select id from v), 5, 'Start of shift', 'Delivery tablets charged and working', 'tick', null, null, null),
 ((select id from v), 6, 'Start of shift', 'Prep list started', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-BOH-CLOSE', 'EAS', 'BOH Closing', 'BOH', 'After service', '22:30', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-BOH-CLOSE', 1, 'published', 'Based on SYD BOH Opening & Closing', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Food and stock', 'All food containers lidded and in fridges or freezers', 'tick', null, null, null),
 ((select id from v), 2, 'Food and stock', 'Stock checked for tomorrow', 'tick', null, 'Beef brisket, rare beef, chicken, hen chicken, prawns', null),
 ((select id from v), 3, 'Food and stock', 'Meat and prawns moved from freezer to defrost if needed', 'tick', null, null, null),
 ((select id from v), 4, 'Food and stock', 'Fridge and freezer temperatures recorded', 'tick', null, null, null),
 ((select id from v), 5, 'Shut down', 'All cooking appliances off', 'tick', null, 'Temperature switches, gas burners, power', null),
 ((select id from v), 6, 'Shut down', 'Fridge and freezer doors closed, seals checked', 'tick', null, null, null),
 ((select id from v), 7, 'Shut down', 'Devices on charge for tomorrow', 'tick', null, null, null),
 ((select id from v), 8, 'Clean down', 'Pots and utensils washed', 'tick', null, null, null),
 ((select id from v), 9, 'Clean down', 'All prep surfaces, appliances and fridge fronts sprayed and wiped', 'tick', null, null, null),
 ((select id from v), 10, 'Clean down', 'Floor swept and mopped with detergent', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-BOH-CLEAN', 'EAS', 'BOH Cleaning', 'BOH', 'Daily / weekly / monthly', '22:30', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-BOH-CLEAN', 1, 'published', 'Based on SYD BOH Cleaning Schedule', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Every day', 'Under induction and grill, grill tray emptied', 'tick', null, null, null),
 ((select id from v), 2, 'Every day', 'Shelves above cooking station', 'tick', null, null, null),
 ((select id from v), 3, 'Every day', 'Noodle and blanching machine cleaned and refilled', 'tick', null, null, null),
 ((select id from v), 4, 'Every day', 'Microwaves, baguette warmer, timers, rice cookers', 'tick', null, null, null),
 ((select id from v), 5, 'Every day', 'Cloths, brushes and scourers washed', 'tick', null, null, null),
 ((select id from v), 6, 'Every day', 'Food probe cleaned and sanitised', 'tick', null, null, null),
 ((select id from v), 7, 'Twice a week', 'Grease traps', 'tick', null, null, null),
 ((select id from v), 8, 'Every week', 'Behind cooking station', 'tick', null, null, null),
 ((select id from v), 9, 'Every week', 'Cutlery and cup drainers, scourer storage', 'tick', null, null, null),
 ((select id from v), 10, 'Every week', 'Inside fridges and freezers', 'tick', null, null, null),
 ((select id from v), 11, 'Every week', 'Extraction grills and hood', 'tick', null, null, null),
 ((select id from v), 12, 'Every week', 'Dishwasher, spray arms, sink tap and hand spray', 'tick', null, null, null),
 ((select id from v), 13, 'Every week', 'Grills', 'tick', null, null, null),
 ((select id from v), 14, 'Every week', 'Electronic fly killer cleaned', 'photo', null, 'Monday morning. Power off at the wall first', null),
 ((select id from v), 15, 'Every week', 'Bin areas including sides and wall', 'tick', null, null, null),
 ((select id from v), 16, 'Every week', 'Drain treatment', 'tick', null, null, null),
 ((select id from v), 17, 'Every month', 'Upper walls', 'tick', null, null, null),
 ((select id from v), 18, 'Every month', 'Evaporators (cold room motors)', 'tick', null, null, null),
 ((select id from v), 19, 'Every month', 'Air con', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-TEMP-COLD', 'EAS', 'Fridge & Freezer Temps', 'BOH', 'Opening and closing', '11:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-TEMP-COLD', 1, 'published', 'WEM Cold Storage Temp Log format. EAS fridge list to confirm', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Cold storage', 'Undercounter fridge (bar)', 'temp', 'F', null, null),
 ((select id from v), 2, 'Cold storage', 'Countertop fridge', 'temp', 'F', null, null),
 ((select id from v), 3, 'Cold storage', 'Kitchen fridge 1', 'temp', 'F', null, 'name to confirm'),
 ((select id from v), 4, 'Cold storage', 'Kitchen fridge 2', 'temp', 'F', null, 'name to confirm'),
 ((select id from v), 5, 'Cold storage', 'Mini freezer (bar)', 'temp', 'Z', null, null),
 ((select id from v), 6, 'Cold storage', 'Kitchen freezer', 'temp', 'Z', null, 'name to confirm');
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-TEMP-COOK', 'EAS', 'Cooking Temps', 'BOH', 'AM and PM', '12:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-TEMP-COOK', 1, 'published', 'WEM Cooking Temp Log', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Core temperature', 'Chicken', 'temp', 'C', null, null),
 ((select id from v), 2, 'Core temperature', 'Pork', 'temp', 'C', null, null),
 ((select id from v), 3, 'Core temperature', 'Lamb', 'temp', 'C', null, null),
 ((select id from v), 4, 'Core temperature', 'Pho broth reheated', 'temp', 'C', null, 'new');
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('EAS-RECEIVE', 'EAS', 'Wembley Delivery', 'BOH', 'On arrival', null, true);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('EAS-RECEIVE', 1, 'published', 'New, from the MVP spec (US-13)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Receive', 'Scan dispatch QR', 'tick', null, null, 'new'),
 ((select id from v), 2, 'Receive', 'Quantities match the dispatch note', 'tick', null, null, 'new'),
 ((select id from v), 3, 'Receive', 'Arrival temperature of chilled items', 'temp', 'F', null, 'new'),
 ((select id from v), 4, 'Receive', 'Labels present with use-by dates', 'tick', null, null, 'new'),
 ((select id from v), 5, 'Receive', 'Stored in fridge straight away', 'tick', null, null, 'new');
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-OPEN', 'WEM', 'Production Opening', 'PROD', 'Start of day', '08:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-OPEN', 1, 'published', 'WEM - BOH Opening Closing (restaurant-only items removed)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Start of day', 'Uniform on, hands washed, hairnet on', 'tick', null, null, null),
 ((select id from v), 2, 'Start of day', 'Fridge and freezer temperatures recorded', 'tick', null, 'Opens the Temperature Check', null),
 ((select id from v), 3, 'Start of day', 'Sink cleaned and cleared', 'tick', null, null, null),
 ((select id from v), 4, 'Start of day', 'Fryer oil checked, fryers on', 'tick', null, 'Skewer fryer 150°C · Twin fryer 180°C', null),
 ((select id from v), 5, 'Start of day', 'Fridge and freezer door seals checked', 'tick', null, null, null),
 ((select id from v), 6, 'Start of day', 'Meat and vegetable stock checked against today''s production', 'tick', null, null, null),
 ((select id from v), 7, 'Start of day', 'All stations ready', 'tick', null, null, null),
 ((select id from v), 8, 'Start of day', 'Safety and hygiene signs displayed in all areas', 'tick', null, null, null),
 ((select id from v), 9, 'First day of the month', 'Last month''s logs reviewed, issues shared with the team', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-CLOSE', 'WEM', 'Production Closing', 'PROD', 'End of day', '17:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-CLOSE', 1, 'published', 'WEM - BOH Opening Closing', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Food and stock', 'All containers lidded, labelled and stored', 'tick', null, null, null),
 ((select id from v), 2, 'Food and stock', 'Stock checked against the stock level list', 'tick', null, null, null),
 ((select id from v), 3, 'Food and stock', 'Tomorrow''s meat and prawns moved to defrost', 'tick', null, 'Beef brisket, rare beef, chicken, hen chicken, prawns', null),
 ((select id from v), 4, 'Food and stock', 'Fridge and freezer temperatures recorded', 'tick', null, null, null),
 ((select id from v), 5, 'Shut down', 'All cooking appliances, gas and power off', 'tick', null, null, null),
 ((select id from v), 6, 'Shut down', 'Taps, gas burners and fryers double-checked off', 'tick', null, null, null),
 ((select id from v), 7, 'Shut down', 'Fridge and freezer doors closed, seals checked', 'tick', null, null, null),
 ((select id from v), 8, 'Shut down', 'Devices on charge', 'tick', null, null, null),
 ((select id from v), 9, 'Clean down', 'Pots and utensils washed', 'tick', null, null, null),
 ((select id from v), 10, 'Clean down', 'Prep surfaces, appliances and fridge fronts sprayed and wiped', 'tick', null, null, null),
 ((select id from v), 11, 'Clean down', 'Floor swept and mopped with detergent', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-CLEAN', 'WEM', 'Production Cleaning', 'PROD', 'Daily / weekly / monthly', '17:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-CLEAN', 1, 'published', 'WEM - BOH Cleaning Schedule (+ fly killer and drain treatment from SYD)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Every day', 'Under induction and grill, grill tray emptied', 'tick', null, null, null),
 ((select id from v), 2, 'Every day', 'Shelves above cooking station', 'tick', null, null, null),
 ((select id from v), 3, 'Every day', 'Noodle and blanching machine cleaned and refilled', 'tick', null, null, null),
 ((select id from v), 4, 'Every day', 'Microwaves, timers, rice cookers', 'tick', null, null, null),
 ((select id from v), 5, 'Every day', 'Cloths, brushes and scourers washed', 'tick', null, null, null),
 ((select id from v), 6, 'Every day', 'Food probe cleaned and sanitised', 'tick', null, null, null),
 ((select id from v), 7, 'Twice a week', 'Grease traps', 'tick', null, null, null),
 ((select id from v), 8, 'Every week', 'Behind cooking station', 'tick', null, null, null),
 ((select id from v), 9, 'Every week', 'Inside fridges and freezers', 'tick', null, null, null),
 ((select id from v), 10, 'Every week', 'Extraction grills and hood', 'tick', null, null, null),
 ((select id from v), 11, 'Every week', 'Dishwasher, spray arms, sink tap and hand spray', 'tick', null, null, null),
 ((select id from v), 12, 'Every week', 'Grills', 'tick', null, null, null),
 ((select id from v), 13, 'Every week', 'Electronic fly killer cleaned', 'photo', null, null, 'from SYD'),
 ((select id from v), 14, 'Every week', 'Bin areas including sides and wall', 'tick', null, null, null),
 ((select id from v), 15, 'Every week', 'Drain treatment', 'tick', null, null, 'from SYD'),
 ((select id from v), 16, 'Every month', 'Upper walls', 'tick', null, null, null),
 ((select id from v), 17, 'Every month', 'Cold room evaporators', 'tick', null, null, null),
 ((select id from v), 18, 'Every month', 'Air con', 'tick', null, null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-TEMP-COLD', 'WEM', 'Fridge & Freezer Temps', 'PROD', 'Opening and closing', '08:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-TEMP-COLD', 1, 'published', 'WEM - Cold Storage Temp Log', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Fridges', 'Fridge 1', 'temp', 'F', null, null),
 ((select id from v), 2, 'Fridges', 'Fridge 2', 'temp', 'F', null, null),
 ((select id from v), 3, 'Fridges', 'Fridge 3', 'temp', 'F', null, null),
 ((select id from v), 4, 'Fridges', 'Fridge 4', 'temp', 'F', null, null),
 ((select id from v), 5, 'Fridges', 'Fridge 5', 'temp', 'F', null, null),
 ((select id from v), 6, 'Freezers', 'Freezer 1', 'temp', 'Z', null, null),
 ((select id from v), 7, 'Freezers', 'Freezer 2', 'temp', 'Z', null, null),
 ((select id from v), 8, 'Freezers', 'Freezer 3', 'temp', 'Z', null, null),
 ((select id from v), 9, 'Freezers', 'Freezer 4', 'temp', 'Z', null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-TEMP-COOK', 'WEM', 'Cooking Temps', 'PROD', 'AM and PM', '10:00', false);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-TEMP-COOK', 1, 'published', 'WEM Cooking Temp Log', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Core temperature', 'Chicken', 'temp', 'C', null, null),
 ((select id from v), 2, 'Core temperature', 'Pork', 'temp', 'C', null, null),
 ((select id from v), 3, 'Core temperature', 'Lamb', 'temp', 'C', null, null),
 ((select id from v), 4, 'Core temperature', 'Tofu', 'temp', 'C', null, null);
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-BATCH', 'WEM', 'Batch, Cool & Label', 'PROD', 'Per batch', null, true);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-BATCH', 1, 'published', 'New, from the MVP spec (US-12)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Batch', 'Recipe and batch size selected', 'tick', null, null, 'new'),
 ((select id from v), 2, 'Batch', 'End-of-cook core temperature', 'temp', 'C', null, 'new'),
 ((select id from v), 3, 'Batch', 'Cooling start time and temperature', 'temp', null, null, 'new'),
 ((select id from v), 4, 'Batch', 'Cooled to fridge temperature within 90 minutes', 'temp', 'F', null, 'new'),
 ((select id from v), 5, 'Batch', 'Label printed and applied', 'tick', null, null, 'new');
insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values ('WEM-DISPATCH', 'WEM', 'Dispatch to Eastcote', 'PROD', 'Before van leaves', '10:30', true);
with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values ('WEM-DISPATCH', 1, 'published', 'New, from the MVP spec (US-13)', now()) returning id)
insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values
 ((select id from v), 1, 'Load', 'Each batch label scanned onto the dispatch', 'tick', null, null, 'new'),
 ((select id from v), 2, 'Load', 'Load temperature of chilled items', 'temp', 'F', null, 'new'),
 ((select id from v), 3, 'Load', 'Driver name recorded', 'text', null, null, 'new'),
 ((select id from v), 4, 'Load', 'Van chilled and clean', 'tick', null, null, 'new');
commit;
