// Builds supabase/seed.sql from data/checklist-library.json.
// Run: node scripts/build-seed.mjs
// The seed holds sites, temperature rules and checklists only. No staff names or PINs.
import { readFileSync, writeFileSync } from "node:fs";

const lib = JSON.parse(readFileSync(new URL("../data/checklist-library.json", import.meta.url), "utf8"));

const DUE = {
  "EAS-FOH-OPEN": "11:30", "EAS-FOH-CLOSE": "22:30", "EAS-FOH-CLEAN": "22:30", "EAS-BAR-PREP": "11:30",
  "EAS-BOH-OPEN": "11:00", "EAS-BOH-CLOSE": "22:30", "EAS-BOH-CLEAN": "22:30", "EAS-TEMP-COLD": "11:00",
  "EAS-TEMP-COOK": "12:00", "WEM-OPEN": "08:00", "WEM-CLOSE": "17:00", "WEM-CLEAN": "17:00",
  "WEM-TEMP-COLD": "08:00", "WEM-TEMP-COOK": "10:00", "WEM-DISPATCH": "10:30",
};

export function ruleFor(limit) {
  if (!limit) return null;
  if (limit.includes("-18")) return "Z";
  if (limit.includes("75")) return "C";
  if (limit.includes("5°C")) return "F";
  return null;
}

const q = (v) => (v === null || v === undefined || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const out = [];
out.push("-- Generated by scripts/build-seed.mjs. Do not edit by hand.");
out.push("begin;");
out.push(`insert into sites (id, name, kind) values ('EAS','Eastcote','restaurant'),('WEM','Wembley','production'),('SYD','Sydenham','restaurant');`);
out.push(`update sites set status='closed', closed_reason='Closed until reopening (owner decision 9 Oct 2026)', closed_at=now() where id='SYD';`);
out.push(`-- Limits must be confirmed by the owner against the approved HACCP plan before go-live (approved_by stays null until then).
insert into temp_rules (code, label, target_max, target_min, legal_max, legal_min) values
 ('F','Fridge / chilled', 5, null, 8, null),
 ('Z','Freezer', -18, null, null, null),
 ('C','Cooking core', null, 75, null, 75);`);

for (const [siteId, site] of Object.entries(lib)) {
  for (const c of site.checklists) {
    out.push(`insert into checklist_templates (id, site_id, name, area, when_label, due_time, is_suggested) values (${q(c.id)}, ${q(siteId)}, ${q(c.name)}, ${q(c.area)}, ${q(c.when)}, ${q(DUE[c.id])}, ${c.tag === "new"});`);
    out.push(`with v as (insert into checklist_versions (template_id, version, status, source_note, published_at) values (${q(c.id)}, 1, 'published', ${q(c.source)}, now()) returning id)`);
    const rows = [];
    let pos = 0;
    for (const [section, items] of c.sections) {
      for (const it of items) {
        pos += 1;
        const rule = it.type === "temp" ? ruleFor(it.limit) : null;
        const tag = it.tag || (c.tag === "new" ? "new" : null);
        rows.push(`((select id from v), ${pos}, ${q(section)}, ${q(it.text)}, ${q(it.type)}, ${q(rule)}, ${q(it.hint || (it.type === "temp" ? null : it.limit))}, ${q(tag)})`);
      }
    }
    out.push(`insert into checklist_items (version_id, position, section, text, answer_type, rule_code, hint, tag) values\n ${rows.join(",\n ")};`);
  }
}
out.push("commit;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");
console.log("supabase/seed.sql written");
